UPDATE PUBLIC.DOG SET PHOTO_PATH = 'dog1.jpeg' WHERE ID = 1;
UPDATE PUBLIC.DOG SET PHOTO_PATH = 'dog2.jpeg' WHERE ID = 2;
UPDATE PUBLIC.DOG SET PHOTO_PATH = 'dog3.jpeg' WHERE ID = 3;
UPDATE PUBLIC.DOG SET PHOTO_PATH = 'dog4.jpeg' WHERE ID = 4;
UPDATE PUBLIC.DOG SET PHOTO_PATH = 'dog5.jpeg' WHERE ID = 5;